services:
  - type: web
    name: kindling
    runtime: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: kindlingdashboard
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: YOU_API_KEY
        sync: false
      - key: RENDER_API_KEY
        sync: false

databases:
  - name: kindlingdashboard
    region: oregon
    plan: free
    databaseName: kindlingdashboard
    user: kindlingdashboard_user
    postgresMajorVersion: 16
